var searchData=
[
  ['package_20executables_0',['Antares Xpansion package executables',['../md_docs_2developer-guide_2xpansion-steps_2index.html#autotoc_md121',1,'']]],
  ['package_20manager_1',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install-from-source_2install-dependencies.html#autotoc_md76',1,'']]],
  ['parameters_2',['parameters',['../md_docs_2reference_2cli.html#autotoc_md236',1,'Command line parameters'],['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md325',1,'Command line parameters']]],
  ['parse_5ftrajectory_5fuser_5ffile_3',['parse_trajectory_user_file',['../classuser__input__translation_1_1UserInputTranslator.html#ad5813f046fe5f99444c42a695c7a3c42',1,'user_input_translation::UserInputTranslator']]],
  ['parser_20translator_4',['Input file parser &amp; translator',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md302',1,'']]],
  ['parsing_5',['User input file parsing',['../md_docs_2reference_2trajectory-investment_2user-input.html',1,'']]],
  ['path_20tt_6',['&lt;tt&gt;--study \&lt;path\&gt;&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md327',1,'']]],
  ['paths_20archives_20file_7',['Study paths / archives file',['../md_docs_2reference_2trajectory-investment_2multiple-problem-generation.html#autotoc_md287',1,'']]],
  ['pathtoyamlconfigfile_5f_8',['pathToYamlConfigFile_',['../classConfigReader.html#a05973b248507ccc4b2daee7aaae8d9c6',1,'ConfigReader']]],
  ['penalties_5f_9',['penalties_',['../classDynamicProgrammingConfigReader.html#a3c9e5de0829552fcbf94384f240d5917',1,'DynamicProgrammingConfigReader']]],
  ['penaltiesnode_5f_10',['penaltiesNode_',['../classDynamicProgrammingConfigReader.html#a0cdfef624a316868ff9265c5690dcf1a',1,'DynamicProgrammingConfigReader']]],
  ['performance_11',['Performance',['../md_docs_2agents_2cpp-conventions.html#autotoc_md23',1,'']]],
  ['performantaressimulation_12',['performAntaresSimulation',['../classProblemGeneration.html#a4a957acac85539627b906c1fca1eeb5f',1,'ProblemGeneration']]],
  ['platforms_13',['Handling Different Platforms',['../md_docs_2developer-guide_2install-from-source_2xpress.html#autotoc_md105',1,'']]],
  ['please_20use_20the_20other_20ones_14',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2overview_2CHANGELOG.html#autotoc_md168',1,'']]],
  ['pluriannual_20vision_15',[' Switching to a pluriannual vision',['../md_docs_2reference_2trajectory-investment_2index.html#autotoc_md273',1,'']]],
  ['pointweekscenariokey_16',['PointWeekScenarioKey',['../structOutput_1_1PointWeekScenarioKey.html',1,'Output']]],
  ['positivefloatvalueerror_17',['PositiveFloatValueError',['../classantares__xpansion_1_1input__checker_1_1PositiveFloatValueError.html',1,'antares_xpansion::input_checker']]],
  ['pre_20build_20dependency_18',['Using pre-build dependency',['../md_docs_2developer-guide_2install-from-source_2install-dependencies.html#autotoc_md81',1,'']]],
  ['predicate_19',['Predicate',['../structPredicate.html',1,'']]],
  ['prepare_5fdrivers_20',['prepare_drivers',['../classantares__xpansion_1_1full__run__driver_1_1FullRunDriver.html#aa41da6a9b74f253aed32501ce17b1fda',1,'antares_xpansion::full_run_driver::FullRunDriver']]],
  ['prepare_5ffolder_21',['prepare_folder',['../classdriver__trajectory_1_1TrajectoryInvestmentDriver.html#a247f5bf7e70d90b0e0b465e2eb0ce74d',1,'driver_trajectory::TrajectoryInvestmentDriver']]],
  ['prepare_5fresolution_5foptions_5ffile_22',['prepare_resolution_options_file',['../classdriver__resolution_1_1TrajectoryResolutionDriver.html#a1b25c911352ddd15806ffaf5b800cf92',1,'driver_resolution::TrajectoryResolutionDriver']]],
  ['presolve_23',['Presolve',['../classPresolve.html',1,'']]],
  ['presolve_20resume_20tt_24',['&lt;tt&gt;--step {full, antares, problem_generation, benders, gems, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md238',1,'']]],
  ['presolve_20tt_25',['&lt;tt&gt;--presolve&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md246',1,'']]],
  ['presolve_5fonly_26',['presolve_only',['../classProblem.html#afc5b4b38128ca8910c2337a78532d0fe',1,'Problem::presolve_only()'],['../classSolverAbstract.html#aba0acac777ba9772c45192f7c592129a',1,'SolverAbstract::presolve_only()'],['../classSolverXpress.html#a3d625d9a37fc658c0484cfce08a15a1a',1,'SolverXpress::presolve_only()'],['../classSolverCbc.html#a15eaa73751b90280e58d70c31adb1f01',1,'SolverCbc::presolve_only()'],['../classSolverClp.html#aab589e50b2dcc4b32fdc08d6f10bec0f',1,'SolverClp::presolve_only()'],['../classNOOPSolver.html#a8e5a2b8c83cc87fe0a9d7328ee4ded70',1,'NOOPSolver::presolve_only()']]],
  ['presolvedata_27',['PresolveData',['../classantares__xpansion_1_1presolve__driver_1_1PresolveData.html',1,'antares_xpansion::presolve_driver']]],
  ['presolvedriver_28',['PresolveDriver',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver.html',1,'antares_xpansion::presolve_driver']]],
  ['presolveexecutionerror_29',['PresolveExecutionError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveExecutionError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveinputpatherror_30',['PresolveInputPathError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveInputPathError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveoptions_31',['PresolveOptions',['../structPresolveOptions.html',1,'']]],
  ['presolveoptionsfileerror_32',['PresolveOptionsFileError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveOptionsFileError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['print_33',['print',['../classSimulationOptions.html#a9f76fa0b9615eac54d0e6394bbe50df8',1,'SimulationOptions::print()'],['../classuser__input__translation_1_1UserInputTranslator.html#aa056f616551e30b61e8d8c9accd287d4',1,'user_input_translation.UserInputTranslator.print()']]],
  ['problem_34',['Problem',['../classProblem.html',1,'']]],
  ['problem_35',['problem',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md130',1,'4- Creation of master problem'],['../md_docs_2reference_2trajectory-investment_2index.html',1,'Trajectory investment problem']]],
  ['problem_20format_20mps_20optimized_20tt_36',['&lt;tt&gt;--problem-format {MPS, OPTIMIZED}&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md242',1,'']]],
  ['problem_20formulation_37',['Master problem formulation',['../md_docs_2reference_2outputs_2others.html#autotoc_md269',1,'']]],
  ['problem_20generation_38',['problem generation',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html',1,'Investment problem generation'],['../md_docs_2reference_2trajectory-investment_2multiple-problem-generation.html',1,'Multiple problem generation']]],
  ['problem_20generation_3a_20tt_20problem_5fgeneration_20tt_39',['2. Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion-steps_2index.html#autotoc_md115',1,'']]],
  ['problem_20retrieval_40',['Antares optimization problem retrieval',['../md_docs_2developer-guide_2xpansion-steps_2antares-solver-problem.html',1,'']]],
  ['problem_5fgeneration_20benders_20gems_20study_5fupdate_20sensitivity_20presolve_20resume_20tt_41',['&lt;tt&gt;--step {full, antares, problem_generation, benders, gems, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md238',1,'']]],
  ['problem_5fgeneration_20tt_42',['2. Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion-steps_2index.html#autotoc_md115',1,'']]],
  ['problemconstructiontest_43',['ProblemConstructionTest',['../classProblemConstructionTest.html',1,'']]],
  ['problemdata_44',['ProblemData',['../structOutput_1_1ProblemData.html',1,'Output::ProblemData'],['../structProblemData.html',1,'ProblemData']]],
  ['problemgeneration_45',['ProblemGeneration',['../classProblemGeneration.html',1,'']]],
  ['problemgenerationexeoptions_46',['ProblemGenerationExeOptions',['../classProblemGenerationExeOptions.html',1,'']]],
  ['problemgenerationexeoptionstest_47',['ProblemGenerationExeOptionsTest',['../classProblemGenerationExeOptionsTest.html',1,'']]],
  ['problemgenerationfilelogger_48',['ProblemGenerationFileLogger',['../classProblemGenerationLog_1_1ProblemGenerationFileLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationforwatervaluecalculation_49',['ProblemGenerationForWaterValueCalculation',['../classProblemGenerationForWaterValueCalculation.html',1,'ProblemGenerationForWaterValueCalculation'],['../classProblemGenerationForWaterValueCalculation.html#a3684ac0496acdddb95b15c51357f774b',1,'ProblemGenerationForWaterValueCalculation::ProblemGenerationForWaterValueCalculation()']]],
  ['problemgenerationilogger_50',['ProblemGenerationILogger',['../classProblemGenerationLog_1_1ProblemGenerationILogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationlogger_51',['ProblemGenerationLogger',['../classProblemGenerationLog_1_1ProblemGenerationLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationloggertest_52',['ProblemGenerationLoggerTest',['../classProblemGenerationLoggerTest.html',1,'']]],
  ['problemgenerationoptimsimu_53',['ProblemGenerationOptimSimu',['../classProblemGenerationOptimSimu.html',1,'ProblemGenerationOptimSimu'],['../classProblemGenerationOptimSimu.html#a302177625f4425c6faa517109be5407a',1,'ProblemGenerationOptimSimu::ProblemGenerationOptimSimu()']]],
  ['problemgenerationoptions_54',['ProblemGenerationOptions',['../classProblemGenerationOptions.html',1,'']]],
  ['problemgenerationostreamlogger_55',['ProblemGenerationOstreamLogger',['../classProblemGenerationLog_1_1ProblemGenerationOstreamLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationspyandmock_56',['ProblemGenerationSpyAndMock',['../classProblemGenerationSpyAndMock.html',1,'']]],
  ['problemgeneratordata_57',['ProblemGeneratorData',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorData.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemgeneratordriver_58',['ProblemGeneratorDriver',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemmanager_59',['ProblemManager',['../classProblemManager.html',1,'']]],
  ['problemmanager_60',['problemManager',['../classEvaluator.html#ae151da44dee8f37fbbcb7893077b4f24',1,'Evaluator::problemManager'],['../classProblemGenerationOptimSimu.html#ab4bcde1d1d02eeb85f51093fa0e7b418',1,'ProblemGenerationOptimSimu::problemManager']]],
  ['problemmodifier_61',['ProblemModifier',['../classProblemModifier.html',1,'']]],
  ['problemmodifiercapex_62',['ProblemModifierCapex',['../classProblemModifierCapex.html',1,'']]],
  ['problemmodifierprojection_63',['ProblemModifierProjection',['../classProblemModifierProjection.html',1,'']]],
  ['problemmodifiertest_64',['ProblemModifierTest',['../classProblemModifierTest.html',1,'']]],
  ['problemmodifiertestmultichronicle_65',['ProblemModifierTestMultiChronicle',['../classProblemModifierTestMultiChronicle.html',1,'']]],
  ['problemmodifiertestwithprofile_66',['ProblemModifierTestWithProfile',['../classProblemModifierTestWithProfile.html',1,'']]],
  ['problemnamecase_67',['ProblemNameCase',['../structProblemNameCase.html',1,'']]],
  ['problems_68',['problems',['../md_docs_2developer-guide_2xpansion-steps_2antares-solver-problem.html#autotoc_md109',1,'&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems'],['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md127',1,'Initial weekly problems']]],
  ['problems_20em_69',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md128',1,'']]],
  ['problems_20of_20annual_20xpansion_20studies_70',['Merging the master problems of annual Xpansion studies',['../md_docs_2reference_2trajectory-investment_2merge-master.html',1,'']]],
  ['problems_20retrieval_3a_20tt_20antares_20tt_71',['1. Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion-steps_2index.html#autotoc_md114',1,'']]],
  ['problems_20with_20tt_20lp_5fnamer_20tt_72',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md124',1,'']]],
  ['problemvariables_73',['ProblemVariables',['../structProblemVariables.html',1,'']]],
  ['problemvariablesfileadapter_74',['ProblemVariablesFileAdapter',['../classProblemVariablesFileAdapter.html',1,'']]],
  ['problemvariablesfromproblemadapter_75',['ProblemVariablesFromProblemAdapter',['../classProblemVariablesFromProblemAdapter.html',1,'']]],
  ['problemvariableszipadapter_76',['ProblemVariablesZipAdapter',['../classProblemVariablesZipAdapter.html',1,'']]],
  ['procedure_77',['Antares Xpansion simulation procedure',['../md_docs_2developer-guide_2xpansion-steps_2index.html',1,'']]],
  ['process_78',['Memory optimization Resolution process',['../md_docs_2reference_2benders_2in-memory-compact-subproblems.html#autotoc_md227',1,'']]],
  ['processsubproblem_79',['ProcessSubproblem',['../classGridEvaluator.html#ad3ccc5fd1e5153603477bec1b846254f',1,'GridEvaluator']]],
  ['profilefilenegativevalue_80',['ProfileFileNegativeValue',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.input_checker.ProfileFileNegativeValue'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileNegativeValue']]],
  ['profilefilenotexists_81',['ProfileFileNotExists',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNotExists.html',1,'antares_xpansion::input_checker']]],
  ['profilefilevalueerror_82',['ProfileFileValueError',['../classantares__xpansion_1_1input__checker_1_1ProfileFileValueError.html',1,'antares_xpansion.input_checker.ProfileFileValueError'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileValueError.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileValueError']]],
  ['profilefilewrongnumberofcolumns_83',['ProfileFileWrongNumberOfcolumns',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfcolumns'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfcolumns']]],
  ['profilefilewrongnumberoflines_84',['ProfileFileWrongNumberOfLines',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfLines'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfLines']]],
  ['profilelinkchecker_85',['ProfileLinkChecker',['../classantares__xpansion_1_1profile__link__checker_1_1ProfileLinkChecker.html',1,'antares_xpansion::profile_link_checker']]],
  ['profilesofdifferentdimensions_86',['ProfilesOfDifferentDimensions',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesOfDifferentDimensions.html',1,'antares_xpansion::candidates_reader']]],
  ['profilesvalueerror_87',['ProfilesValueError',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesValueError.html',1,'antares_xpansion::candidates_reader']]],
  ['project_20structure_88',['Project Structure',['../md_docs_2agents_2cpp-conventions.html#autotoc_md17',1,'Project Structure'],['../md_docs_2agents_2python-conventions.html#autotoc_md31',1,'Project Structure']]],
  ['pshiftmax_5f_89',['pShiftMax_',['../structLinkdataRecord_1_1FileColumns.html#a8d83f0f99914a833dfb34896ab69be36',1,'LinkdataRecord::FileColumns']]],
  ['pshiftmin_5f_90',['pShiftMin_',['../structLinkdataRecord_1_1FileColumns.html#a087c9dfcfef544c84f61925adcc1a7d4',1,'LinkdataRecord::FileColumns']]],
  ['py_20tt_91',['Key &lt;tt&gt;Given&lt;/tt&gt; steps (&lt;tt&gt;steps/given.py&lt;/tt&gt;)',['../md_docs_2agents_2testing.html#autotoc_md62',1,'']]],
  ['pytest_92',['Python Tests (pytest)',['../md_docs_2agents_2testing.html#autotoc_md54',1,'']]],
  ['python_93',['Unit Tests Only (C++ and Python)',['../md_docs_2agents_2testing.html#autotoc_md41',1,'']]],
  ['python_20conventions_94',['Python Conventions',['../md_docs_2agents_2python-conventions.html',1,'']]],
  ['python_20orchestrator_20tt_20get_5fnames_20tt_95',['Python orchestrator &lt;tt&gt;get_names&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md123',1,'']]],
  ['python_20tests_20pytest_96',['Python Tests (pytest)',['../md_docs_2agents_2testing.html#autotoc_md54',1,'']]],
  ['python_20unit_20tests_20only_97',['Python Unit Tests Only',['../md_docs_2agents_2testing.html#autotoc_md43',1,'']]],
  ['python_20version_98',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install-from-source_2development-requirements.html#autotoc_md71',1,'']]],
  ['python_20version_20python_20version_99',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install-from-source_2development-requirements.html#autotoc_md71',1,'']]]
];
