var searchData=
[
  ['c_20and_20python_0',['Unit Tests Only (C++ and Python)',['../md_docs_2agents_2testing.html#autotoc_md41',1,'']]],
  ['c_20conventions_1',['C++ Conventions',['../md_docs_2agents_2cpp-conventions.html',1,'']]],
  ['c_20tests_20google_20test_2',['C++ Tests (Google Test)',['../md_docs_2agents_2testing.html#autotoc_md50',1,'']]],
  ['c_20unit_20tests_20only_3',['C++ Unit Tests Only',['../md_docs_2agents_2testing.html#autotoc_md42',1,'']]],
  ['c_20version_4',['C++ version',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md145',1,'']]],
  ['cache_5fproblems_20tt_5',['&lt;tt&gt;--cache_problems&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md249',1,'']]],
  ['calling_20the_20presolve_6',['Calling the presolve',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html#autotoc_md323',1,'']]],
  ['can_20be_20computed_7',['Use cases where water values can be computed',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md300',1,'']]],
  ['candidate_8',['Candidate',['../classCandidate.html',1,'']]],
  ['candidate_20constraints_9',['3- Read additional candidate constraints',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md198',1,'']]],
  ['candidate_20links_10',['Updates of candidate links',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md252',1,'']]],
  ['candidatecosts_11',['CandidateCosts',['../structMergeMasterTrajectoryMPS_1_1CandidateCosts.html',1,'MergeMasterTrajectoryMPS']]],
  ['candidatedata_12',['CandidateData',['../structCandidateData.html',1,'CandidateData'],['../structOutput_1_1CandidateData.html',1,'Output::CandidateData']]],
  ['candidateduplicationdetected_13',['CandidateDuplicationDetected',['../classActiveLinksBuilder_1_1CandidateDuplicationDetected.html',1,'ActiveLinksBuilder']]],
  ['candidatefilenotfound_14',['CandidateFileNotFound',['../classantares__xpansion_1_1profile__link__checker_1_1ProfileLinkChecker_1_1CandidateFileNotFound.html',1,'antares_xpansion::profile_link_checker::ProfileLinkChecker']]],
  ['candidatefilewrongtypevalue_15',['CandidateFileWrongTypeValue',['../classantares__xpansion_1_1input__checker_1_1CandidateFileWrongTypeValue.html',1,'antares_xpansion::input_checker']]],
  ['candidateinstalledprofilecolumnnumbermismatch_16',['CandidateInstalledProfileColumnNumberMismatch',['../classantares__xpansion_1_1chronicles__checker_1_1CandidateInstalledProfileColumnNumberMismatch.html',1,'antares_xpansion::chronicles_checker']]],
  ['candidateinstalledprofilecolumnnumbermismatchwithprofile_17',['CandidateInstalledProfileColumnNumberMismatchWithProfile',['../classantares__xpansion_1_1chronicles__checker_1_1CandidateInstalledProfileColumnNumberMismatchWithProfile.html',1,'antares_xpansion::chronicles_checker']]],
  ['candidatelinkwithoutseparator_18',['CandidateLinkWithoutSeparator',['../classantares__xpansion_1_1input__checker_1_1CandidateLinkWithoutSeparator.html',1,'antares_xpansion::input_checker']]],
  ['candidatelog_19',['CandidateLog',['../classxpansion_1_1logger_1_1CandidateLog.html',1,'xpansion::logger']]],
  ['candidatenameduplicatederror_20',['CandidateNameDuplicatedError',['../classantares__xpansion_1_1input__checker_1_1CandidateNameDuplicatedError.html',1,'antares_xpansion::input_checker']]],
  ['candidatenotfound_21',['CandidateNotFound',['../classantares__xpansion_1_1candidates__reader_1_1CandidateNotFound.html',1,'antares_xpansion::candidates_reader']]],
  ['candidateprofilecolumnnumbermismatch_22',['CandidateProfileColumnNumberMismatch',['../classantares__xpansion_1_1chronicles__checker_1_1CandidateProfileColumnNumberMismatch.html',1,'antares_xpansion::chronicles_checker']]],
  ['candidates_23',['candidates',['../md_docs_2user-guide_2trajectory-investment_2user-input.html#autotoc_md372',1,'A note on candidates'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md266',1,'Additional characteristics for links of investment candidates'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md229',1,'Decommissioning candidates'],['../md_docs_2user-guide_2get-started_2candidate-definition.html',1,'Define the candidates'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md226',1,'Examples of candidates'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md265',1,'Fixed-cost annuity for decommissioning candidates'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md264',1,'Fixed-cost annuity for investment candidates']]],
  ['candidates_20and_20get_20link_20column_20id_24',['1- Read candidates and get link column ID',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md194',1,'']]],
  ['candidates_20in_20tt_20candidates_20ini_20tt_25',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md212',1,'']]],
  ['candidates_20ini_20tt_26',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md212',1,'']]],
  ['candidates_20ini_20tt_20file_27',['Overview of the &lt;tt&gt;candidates.ini&lt;/tt&gt; file',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md213',1,'']]],
  ['candidates_20on_20the_20same_20link_28',['Several investment candidates on the same link',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md228',1,'']]],
  ['candidates_5fini_5ffilepath_29',['candidates_ini_filepath',['../classantares__xpansion_1_1config__loader_1_1XpansionSettingsReader.html#a411fce38086a815b5914b99e1d6d5075',1,'antares_xpansion::config_loader::XpansionSettingsReader']]],
  ['candidatesinireader_30',['CandidatesINIReader',['../classCandidatesINIReader.html',1,'']]],
  ['candidatesinireadertest_31',['CandidatesINIReaderTest',['../classCandidatesINIReaderTest.html',1,'']]],
  ['candidatesreader_32',['CandidatesReader',['../classantares__xpansion_1_1candidates__reader_1_1CandidatesReader.html',1,'antares_xpansion::candidates_reader']]],
  ['candidatetype_33',['CandidateType',['../classuser__input__translation_1_1CandidateType.html',1,'user_input_translation']]],
  ['candidatewasnotaddedinproblem_34',['CandidateWasNotAddedInProblem',['../classProblemModifier_1_1CandidateWasNotAddedInProblem.html',1,'ProblemModifier']]],
  ['capacities_35',['Decommissioning decisions for thermal capacities',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md263',1,'']]],
  ['capacity_36',['capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md261',1,'Investment in renewable generation capacity'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md260',1,'Investment in thermal generation capacity']]],
  ['capacity_20and_20capacity_20of_20the_20antares_20study_37',['Link between invested capacity and capacity of the Antares study',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md224',1,'']]],
  ['capacity_20and_20investment_20cost_38',['Invested capacity and investment cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md327',1,'']]],
  ['capacity_20between_20two_20areas_39',['Investment in transmission capacity between two areas',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md259',1,'']]],
  ['capacity_20of_20the_20antares_20study_40',['Link between invested capacity and capacity of the Antares study',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md224',1,'']]],
  ['capacity_20tt_41',['&lt;tt&gt;already-installed-capacity&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md221',1,'']]],
  ['capacity_5ffile_42',['capacity_file',['../classantares__xpansion_1_1config__loader_1_1XpansionSettingsReader.html#a8bcb0071dd135f3c24e56506f56cb675',1,'antares_xpansion::config_loader::XpansionSettingsReader']]],
  ['capacitydirnotfound_43',['CapacityDirNotFound',['../classantares__xpansion_1_1profile__link__checker_1_1ProfileLinkChecker_1_1CapacityDirNotFound.html',1,'antares_xpansion.profile_link_checker.ProfileLinkChecker.CapacityDirNotFound'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1CapacityDirNotFound.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.CapacityDirNotFound']]],
  ['capturedrow_44',['CapturedRow',['../structCapturingSolverForAlphas_1_1CapturedRow.html',1,'CapturingSolverForAlphas']]],
  ['capturingsolverforalphas_45',['CapturingSolverForAlphas',['../classCapturingSolverForAlphas.html',1,'']]],
  ['carlo_20year_46',['Using different profiles depending on the Monte-Carlo year',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md225',1,'']]],
  ['cases_20where_20water_20values_20can_20be_20computed_47',['Use cases where water values can be computed',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md300',1,'']]],
  ['changelog_48',['Antares-Xpansion changelog',['../md_docs_2changelog_2CHANGELOG.html',1,'']]],
  ['changes_49',['Study format changes',['../md_docs_2changelog_2format__changes.html',1,'']]],
  ['characteristics_20for_20links_20of_20investment_20candidates_50',['Additional characteristics for links of investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md266',1,'']]],
  ['characterization_20of_20investment_20candidates_20in_20tt_20candidates_20ini_20tt_51',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md212',1,'']]],
  ['check_5foptions_52',['check_options',['../namespaceantares__xpansion_1_1input__checker.html#a6384647641c8b6636e1e0b97286ff37f',1,'antares_xpansion::input_checker']]],
  ['check_5fsolver_53',['check_solver',['../classantares__xpansion_1_1xpansion__study__reader_1_1XpansionStudyReader.html#a63d08cd80d7914beac6a2b9765160469',1,'antares_xpansion::xpansion_study_reader::XpansionStudyReader']]],
  ['check_5fweights_5ffile_54',['check_weights_file',['../classantares__xpansion_1_1xpansion__study__reader_1_1XpansionStudyReader.html#a6ea6408ddece0021001a8ac9b80d3369',1,'antares_xpansion::xpansion_study_reader::XpansionStudyReader']]],
  ['checkandreturnconstraintname_55',['checkAndReturnConstraintName',['../classAdditionalConstraints.html#a263e06560f6a90ccd6abd772d56033a5',1,'AdditionalConstraints']]],
  ['checkandreturnsectionrhs_56',['checkAndReturnSectionRhs',['../classAdditionalConstraints.html#ad0035f8aa50453c7bb9be543baf96b46',1,'AdditionalConstraints']]],
  ['checkandreturnsectionsign_57',['checkAndReturnSectionSign',['../classAdditionalConstraints.html#a83c5124597c4c92954de8abf4f5d329c',1,'AdditionalConstraints']]],
  ['checkweightsfile_58',['CheckWeightsFile',['../classWeightsFileReader.html#a46e3c77a59329240219130b3fd4e989b',1,'WeightsFileReader']]],
  ['chg_5fbounds_59',['chg_bounds',['../classProblem.html#a4bc726350bcf61005c30cc61e6018b4e',1,'Problem::chg_bounds()'],['../classSolverAbstract.html#a6616ffd2a1efc07380de0fadface4fe2',1,'SolverAbstract::chg_bounds()'],['../classSolverXpress.html#ae13bac444a57274195b6fef413fbff75',1,'SolverXpress::chg_bounds()'],['../classSolverCbc.html#acb9778e4fad177b77a72e178a6728093',1,'SolverCbc::chg_bounds()'],['../classSolverClp.html#a3201c8c68c482a5910950c323095eb5e',1,'SolverClp::chg_bounds()'],['../classNOOPSolver.html#a32d5dffe3a65fcf81fb9db31f7c94a8e',1,'NOOPSolver::chg_bounds()']]],
  ['chg_5fcoef_60',['chg_coef',['../classProblem.html#ad0ee54139145f03b9f188d40cb7a0856',1,'Problem::chg_coef()'],['../classSolverAbstract.html#ad82a76bf5cc2419cae4aa0bb72216289',1,'SolverAbstract::chg_coef()'],['../classSolverXpress.html#a036c80d5dc830651349d5d32c8822a0b',1,'SolverXpress::chg_coef()'],['../classSolverCbc.html#adb09607d1ed3545e47bb822a99f0afea',1,'SolverCbc::chg_coef()'],['../classSolverClp.html#a8734e00ca2a5f2619231801afd915a62',1,'SolverClp::chg_coef()'],['../classNOOPSolver.html#ac5cbd694fe01554c2fdb75a895e04551',1,'NOOPSolver::chg_coef()']]],
  ['chg_5fcol_5fname_61',['chg_col_name',['../classProblem.html#af4b08904684db423cee3a8f8c58ff800',1,'Problem::chg_col_name()'],['../classSolverAbstract.html#aa164e8aa26670bb0e15a6f0c554a9a0d',1,'SolverAbstract::chg_col_name()'],['../classSolverXpress.html#aeff0db8ee002795490782b17cd4be857',1,'SolverXpress::chg_col_name()'],['../classSolverCbc.html#a37c19e7a8d7df5fa0ee9550fb106713b',1,'SolverCbc::chg_col_name()'],['../classSolverClp.html#ac4b757e0d5d890cecc37f2852dddb12c',1,'SolverClp::chg_col_name()'],['../classNOOPSolver.html#a57e04da723bc11414198b3963ebc3a36',1,'NOOPSolver::chg_col_name()']]],
  ['chg_5fcol_5ftype_62',['chg_col_type',['../classProblem.html#acd23d7ef0eabbfeaca4b371d48538d8e',1,'Problem::chg_col_type()'],['../classSolverAbstract.html#a05faccb2ae9a6abbc1c2f86ee38888dc',1,'SolverAbstract::chg_col_type()'],['../classSolverXpress.html#ad640fc6e5e2bfa1d8fc88b444fe21b7e',1,'SolverXpress::chg_col_type()'],['../classSolverCbc.html#aff1912b473ef8e6db7db523deb6d7676',1,'SolverCbc::chg_col_type()'],['../classSolverClp.html#a311bc635068f38397b0fc07c68877f5d',1,'SolverClp::chg_col_type()'],['../classNOOPSolver.html#a066d705a508b9dcbdffc75ebcc9bef29',1,'NOOPSolver::chg_col_type()']]],
  ['chg_5fobj_63',['chg_obj',['../classProblem.html#a824fa83671eb0273279277b1867b6909',1,'Problem::chg_obj()'],['../classSolverAbstract.html#a7bae7d1aa559bb2e4197eb3d16e494d7',1,'SolverAbstract::chg_obj()'],['../classSolverXpress.html#a9d20d096f5eba5bd073e0b2d7554428b',1,'SolverXpress::chg_obj()'],['../classSolverCbc.html#a86ceda2f93815c8e027bd739aedd81e0',1,'SolverCbc::chg_obj()'],['../classSolverClp.html#a4c205dc2a3d6aaa45028b24327e0b707',1,'SolverClp::chg_obj()'],['../classNOOPSolver.html#a56d05faae50c866e5f6155e9ec8923e8',1,'NOOPSolver::chg_obj()']]],
  ['chg_5fobj_5fdirection_64',['chg_obj_direction',['../classProblem.html#ae0340e6b71a6b4ee444c8638a868f63e',1,'Problem::chg_obj_direction()'],['../classSolverAbstract.html#a4e2183428adf3fd1df10a56975412a9e',1,'SolverAbstract::chg_obj_direction()'],['../classSolverXpress.html#ab77c8e1bedcd92a3ccad976025525971',1,'SolverXpress::chg_obj_direction()'],['../classSolverCbc.html#ade13a11f0442b0f3670454e8e3805856',1,'SolverCbc::chg_obj_direction()'],['../classSolverClp.html#a3478e58893882818147e647849e1a627',1,'SolverClp::chg_obj_direction()'],['../classNOOPSolver.html#ac86018eac1d6e75a9ff5ae94eccab32a',1,'NOOPSolver::chg_obj_direction()']]],
  ['chg_5frhs_65',['chg_rhs',['../classProblem.html#a7f85cacdc241722dad22e570957890aa',1,'Problem::chg_rhs()'],['../classSolverAbstract.html#ad258bd76e2f7d5c1103d05ffb79b4c59',1,'SolverAbstract::chg_rhs()'],['../classSolverXpress.html#aea4b1d26fe9cadc968305c6c2fe3b442',1,'SolverXpress::chg_rhs()'],['../classSolverCbc.html#a8fa0d0e8fab67cd8f07930d8337549a4',1,'SolverCbc::chg_rhs()'],['../classSolverClp.html#af29c592ff80e778ee906f10a40648192',1,'SolverClp::chg_rhs()'],['../classNOOPSolver.html#a548d8819117967d3de06a280a60b399d',1,'NOOPSolver::chg_rhs()']]],
  ['chg_5frow_5fname_66',['chg_row_name',['../classProblem.html#a13f183f9af6db636f61e0e919ad8f834',1,'Problem::chg_row_name()'],['../classSolverAbstract.html#ad992af8d12855a30f1d0c45daf988753',1,'SolverAbstract::chg_row_name()'],['../classSolverXpress.html#a9e3d875088b872c4b8153c2067b8fed4',1,'SolverXpress::chg_row_name()'],['../classSolverCbc.html#a91961aef6dbf88d420c029eed8a948ab',1,'SolverCbc::chg_row_name()'],['../classSolverClp.html#aa059147184d5df7e754b5ba829034961',1,'SolverClp::chg_row_name()'],['../classNOOPSolver.html#a5f8d90f146d65b8c4f4e1a3bf62fab5b',1,'NOOPSolver::chg_row_name()']]],
  ['chroniclechecker_67',['ChronicleChecker',['../classantares__xpansion_1_1chronicles__checker_1_1ChronicleChecker.html',1,'antares_xpansion::chronicles_checker']]],
  ['chronicleprovidertest_68',['ChronicleProviderTest',['../classChronicleProviderTest.html',1,'']]],
  ['chronicletest_69',['ChronicleTest',['../classChronicleTest.html',1,'']]],
  ['ci_70',['CI',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md62',1,'CI'],['../md_docs_2changelog_2CHANGELOG.html#autotoc_md68',1,'CI']]],
  ['ci_20requirements_71',['CI Requirements',['../md_docs_2agents_2testing.html#autotoc_md58',1,'']]],
  ['class_72',['class',['../classclass.html',1,'']]],
  ['clock_73',['Clock',['../classClock.html',1,'']]],
  ['clockmock_74',['ClockMock',['../classClockMock.html',1,'']]],
  ['clone_5fmatrix_5fto_5fnew_5fprob_75',['clone_matrix_to_new_prob',['../classSolverXpress.html#a301b344a1be679943831e496432e94d9',1,'SolverXpress']]],
  ['closeunsafe_76',['CloseUnsafe',['../classArchiveWriter.html#a38ac4d8d0cdcc1319696927f2bb0174d',1,'ArchiveWriter']]],
  ['cmake_77',['Configure build with CMake',['../md_docs_2developer-guide_2install__from__sources_23-Build.html#autotoc_md159',1,'']]],
  ['cmake_20version_78',['@ref &quot;cmake-version&quot; &quot;CMake version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md146',1,'']]],
  ['cmake_20version_20cmake_20version_79',['@ref &quot;cmake-version&quot; &quot;CMake version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md146',1,'']]],
  ['code_20content_80',['Source Code Content',['../index.html#autotoc_md9',1,'']]],
  ['code_20loads_20xpress_81',['How the Code Loads Xpress',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md171',1,'']]],
  ['code_20style_82',['Code Style',['../md_docs_2agents_2cpp-conventions.html#autotoc_md12',1,'Code Style'],['../md_docs_2agents_2python-conventions.html#autotoc_md27',1,'Code Style']]],
  ['coin_20tt_83',['&lt;tt&gt;--solver {xpress, coin}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md308',1,'']]],
  ['column_20id_84',['1- Read candidates and get link column ID',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md194',1,'']]],
  ['column_20id_20mapping_20file_85',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md200',1,'']]],
  ['columntochange_86',['ColumnToChange',['../structColumnToChange.html',1,'']]],
  ['command_20line_20parameters_87',['Command line parameters',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md236',1,'Command line parameters'],['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md305',1,'Command line parameters']]],
  ['command_20line_20usage_88',['Command line usage',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md234',1,'Command line usage'],['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md303',1,'Command line usage'],['../index.html#autotoc_md7',1,'Command-line usage']]],
  ['computation_89',['Water Values Computation',['../md_docs_2user-guide_2get-started_2water-values-computation.html',1,'']]],
  ['computation_90',['From economic concept to numerical computation',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md296',1,'']]],
  ['compute_91',['compute',['../classBellmanValues.html#a2de0fad8531906316b8e0a33d245abee',1,'BellmanValues']]],
  ['compute_5fnode_5fduration_92',['compute_node_duration',['../classuser__input__translation_1_1UserInputTranslator.html#ad05f72e31d614d355f4bdb566d95f00a',1,'user_input_translation::UserInputTranslator']]],
  ['compute_5fnode_5ffull_5fprobability_93',['compute_node_full_probability',['../classuser__input__translation_1_1UserInputTranslator.html#a2b2f4498f69554ce1805d0bfdab6a90c',1,'user_input_translation::UserInputTranslator']]],
  ['computecostsandduals_94',['ComputeCostsAndDuals',['../classGridEvaluator.html#ab80834dbbb3439c7da1b376f7245c891',1,'GridEvaluator::ComputeCostsAndDuals()'],['../structBellmanValuesComputeTest_1_1GridEvaluatorMock.html#a107a207fde69cbafc066e0f74f341e88',1,'BellmanValuesComputeTest::GridEvaluatorMock::ComputeCostsAndDuals()']]],
  ['computecriterion_95',['ComputeCriterion',['../classBenders_1_1Criterion_1_1CriterionComputation.html#ab2bde9110d81505551c5f526bc840535',1,'Benders::Criterion::CriterionComputation']]],
  ['computed_96',['Use cases where water values can be computed',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md300',1,'']]],
  ['computenewcapacities_97',['computeNewCapacities',['../classStudyUpdateLinkParameterStrategy.html#a7bc3dca99fbf78003a2438a394afcef0',1,'StudyUpdateLinkParameterStrategy']]],
  ['concept_20to_20numerical_20computation_98',['From economic concept to numerical computation',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md296',1,'']]],
  ['concurrentinsertionmap_99',['ConcurrentInsertionMap',['../structOutput_1_1ConcurrentInsertionMap.html',1,'Output']]],
  ['concurrentinsertionmap_3c_20output_3a_3apointweekscenariokey_2c_20plaindata_3a_3asubproblemdata_20_3e_100',['ConcurrentInsertionMap&lt; Output::PointWeekScenarioKey, PlainData::SubProblemData &gt;',['../structOutput_1_1ConcurrentInsertionMap.html',1,'Output']]],
  ['configdirectories_101',['ConfigDirectories',['../structConfigurationManager_1_1ConfigDirectories.html',1,'ConfigurationManager']]],
  ['configfileparser_102',['ConfigFileParser',['../classantares__xpansion_1_1config__file__parser_1_1ConfigFileParser.html',1,'antares_xpansion::config_file_parser']]],
  ['configloader_103',['ConfigLoader',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html',1,'antares_xpansion::config_loader']]],
  ['configparameters_104',['ConfigParameters',['../classantares__xpansion_1_1xpansionConfig_1_1ConfigParameters.html',1,'antares_xpansion::xpansionConfig']]],
  ['configuration_105',['Configuration',['../md_docs_2agents_2python-conventions.html#autotoc_md36',1,'']]],
  ['configuration_20for_20antares_20xpansion_106',['Specific configuration for Antares-Xpansion',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md185',1,'']]],
  ['configurationmanager_107',['ConfigurationManager',['../classConfigurationManager.html',1,'']]],
  ['configure_20build_20with_20cmake_108',['Configure build with CMake',['../md_docs_2developer-guide_2install__from__sources_23-Build.html#autotoc_md159',1,'']]],
  ['configure_20vcpkg_109',['Configure VCPKG',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md151',1,'']]],
  ['conflictingparameters_110',['ConflictingParameters',['../classProblemGenerationOptions_1_1ConflictingParameters.html',1,'ProblemGenerationOptions']]],
  ['constrained_20investment_20problem_111',['Reliability-constrained investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md338',1,'']]],
  ['constraintoperatorenum_112',['ConstraintOperatorEnum',['../classuser__input__translation_1_1ConstraintOperatorEnum.html',1,'user_input_translation']]],
  ['constraints_113',['constraints',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md198',1,'3- Read additional candidate constraints'],['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md345',1,'Trajectory constraints']]],
  ['constraints_20for_20the_20investment_20problem_114',['Constraints (for the investment problem)',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md332',1,'']]],
  ['constraints_20reference_20file_115',['Weights / additional constraints reference file',['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html#autotoc_md353',1,'']]],
  ['constraints_20translation_116',['Trajectory constraints translation',['../md_docs_2user-guide_2trajectory-investment_2user-input.html#autotoc_md373',1,'']]],
  ['constraints_20tt_117',['&lt;tt&gt;additional-constraints&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md287',1,'']]],
  ['constraintsfilereader_118',['ConstraintsFileReader',['../classConstraintsFileReader.html',1,'']]],
  ['constrainttypeenum_119',['ConstraintTypeEnum',['../classuser__input__translation_1_1ConstraintTypeEnum.html',1,'user_input_translation']]],
  ['constructadditionalconstraints_120',['constructAdditionalConstraints',['../classAdditionalConstraints.html#a0616e02d19f02fc94b1c26fe40265278',1,'AdditionalConstraints']]],
  ['content_121',['Source Code Content',['../index.html#autotoc_md9',1,'']]],
  ['contents_122',['Table of Contents',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md164',1,'']]],
  ['context_123',['Context',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md382',1,'Context'],['..//github/workspace/tests/end_to_end/grid_search/README.md#autotoc_md393',1,'Context'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md398',1,'Context']]],
  ['contributors_124',['New Contributors',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md83',1,'']]],
  ['conventions_125',['Conventions',['../md_docs_2agents_2cpp-conventions.html',1,'C++ Conventions'],['../md_docs_2agents_2python-conventions.html',1,'Python Conventions']]],
  ['convert_3c_20criterionsingleinputdata_20_3e_126',['convert&lt; CriterionSingleInputData &gt;',['../classYAML_1_1convert_3_01CriterionSingleInputData_01_4.html',1,'YAML']]],
  ['convert_3c_20outerloopcriterioninputdata_20_3e_127',['convert&lt; OuterLoopCriterionInputData &gt;',['../classYAML_1_1convert_3_01OuterLoopCriterionInputData_01_4.html',1,'YAML']]],
  ['copy_5fsolver_128',['copy_solver',['../classSolverFactory.html#a011cb273e705acc76c0bf4a513827fb0',1,'SolverFactory']]],
  ['corruptedlockerfile_129',['CorruptedLockerFile',['../classantares__xpansion_1_1study__locker_1_1StudyLocker_1_1CorruptedLockerFile.html',1,'antares_xpansion::study_locker::StudyLocker']]],
  ['cost_130',['cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md327',1,'Invested capacity and investment cost'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md328',1,'Operating cost']]],
  ['cost_20annuity_20for_20decommissioning_20candidates_131',['Fixed-cost annuity for decommissioning candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md265',1,'']]],
  ['cost_20annuity_20for_20investment_20candidates_132',['Fixed-cost annuity for investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md264',1,'']]],
  ['cost_20as_20the_20solution_20of_20an_20antares_20simulation_133',['The operating cost as the solution of an Antares simulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md329',1,'']]],
  ['cost_20per_20mw_20tt_134',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md217',1,'']]],
  ['costs_135',['costs',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md331',1,'Summary of the costs'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md326',1,'Variables and costs']]],
  ['couldnotreadareafield_136',['CouldNotReadAreaField',['../classBenders_1_1Criterion_1_1CouldNotReadAreaField.html',1,'Benders::Criterion']]],
  ['couldnotreadcriterionfield_137',['CouldNotReadCriterionField',['../classBenders_1_1Criterion_1_1CouldNotReadCriterionField.html',1,'Benders::Criterion']]],
  ['couplingmapgenerator_138',['CouplingMapGenerator',['../classCouplingMapGenerator.html',1,'']]],
  ['coverage_139',['With Coverage',['../md_docs_2agents_2testing.html#autotoc_md46',1,'']]],
  ['cpu_20tt_140',['&lt;tt&gt;--antares-n-cpu&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md244',1,'']]],
  ['create_5fsolver_141',['create_solver',['../classSolverFactory.html#a97e25ebe7f69c4a1a2749145869b38e6',1,'SolverFactory::create_solver(const std::string &amp;solver_name) const'],['../classSolverFactory.html#acd204f241923e841792cf69427c848e8',1,'SolverFactory::create_solver(const SolverConfig &amp;solver_config) const']]],
  ['createfixture_142',['CreateFixture',['../classCreateFixture.html',1,'']]],
  ['createmasterproblem_143',['createMasterProblem',['../classMergeMPSTest.html#a073cb28c5dee7dfe4eb64305b6e046b9',1,'MergeMPSTest']]],
  ['createsatelliteproblem_144',['createSatelliteProblem',['../classMergeMPSTest.html#a5987f5784590b6c016bcbad5b019fabd',1,'MergeMPSTest']]],
  ['creation_145',['creation',['../md_docs_2developer-guide_2install__from__sources_25-Installer-creation.html',1,'Installer creation'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md272',1,'Sensitivity input file creation']]],
  ['creation_20of_20a_20variable_20column_20id_20mapping_20file_146',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md200',1,'']]],
  ['creation_20of_20master_20problem_147',['4- Creation of master problem',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md199',1,'']]],
  ['criteriacurrentiterationdata_148',['CriteriaCurrentIterationData',['../structCriteriaCurrentIterationData.html',1,'']]],
  ['criterion_149',['criterion',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html',1,'Adequacy criterion'],['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md209',1,'Launching the optimization with the adequacy criterion']]],
  ['criterion_20in_20tt_20adequacy_5fcriterion_20yml_20tt_150',['Input data for adequacy criterion in &lt;tt&gt;adequacy_criterion.yml&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md208',1,'']]],
  ['criterioncomputation_151',['CriterionComputation',['../classBenders_1_1Criterion_1_1CriterionComputation.html',1,'Benders::Criterion::CriterionComputation'],['../classBenders_1_1Criterion_1_1CriterionComputation.html#aafb513fd40fb290e9617d8acd13f34b1',1,'Benders::Criterion::CriterionComputation::CriterionComputation()=default'],['../classBenders_1_1Criterion_1_1CriterionComputation.html#ab7def1ebc37ba5b2219349e411a0187d',1,'Benders::Criterion::CriterionComputation::CriterionComputation(const CriterionInputData &amp;criterion_input_data)']]],
  ['criterioncouldnotbesatisfied_152',['CriterionCouldNotBeSatisfied',['../classOuterloop_1_1CriterionCouldNotBeSatisfied.html',1,'Outerloop']]],
  ['criterioninputdata_153',['CriterionInputData',['../classBenders_1_1Criterion_1_1CriterionInputData.html',1,'Benders::Criterion']]],
  ['criterioninputfileerror_154',['CriterionInputFileError',['../classBenders_1_1Criterion_1_1CriterionInputFileError.html',1,'Benders::Criterion']]],
  ['criterioninputfileisempty_155',['CriterionInputFileIsEmpty',['../classBenders_1_1Criterion_1_1CriterionInputFileIsEmpty.html',1,'Benders::Criterion']]],
  ['criterioninputfilenopatternfound_156',['CriterionInputFileNoPatternFound',['../classBenders_1_1Criterion_1_1CriterionInputFileNoPatternFound.html',1,'Benders::Criterion']]],
  ['criterioninputfromyaml_157',['CriterionInputFromYaml',['../classBenders_1_1Criterion_1_1CriterionInputFromYaml.html',1,'Benders::Criterion']]],
  ['criterioninputpatternsshouldbearray_158',['CriterionInputPatternsShouldBeArray',['../classBenders_1_1Criterion_1_1CriterionInputPatternsShouldBeArray.html',1,'Benders::Criterion']]],
  ['criterionpattern_159',['CriterionPattern',['../classBenders_1_1Criterion_1_1CriterionPattern.html',1,'Benders::Criterion::CriterionPattern'],['../classBenders_1_1Criterion_1_1CriterionPattern.html#a64c62a0464bb2508709063eb352da908',1,'Benders::Criterion::CriterionPattern::CriterionPattern()']]],
  ['criterionsingleinputdata_160',['CriterionSingleInputData',['../classBenders_1_1Criterion_1_1CriterionSingleInputData.html',1,'Benders::Criterion::CriterionSingleInputData'],['../classBenders_1_1Criterion_1_1CriterionSingleInputData.html#a676b2c8a9e865b6a3cb3610ee27765be',1,'Benders::Criterion::CriterionSingleInputData::CriterionSingleInputData()']]],
  ['csv_161',['Input file grid.csv',['../md_docs_2user-guide_2get-started_2water-values-computation.html#autotoc_md298',1,'']]],
  ['currentiterationdata_162',['CurrentIterationData',['../structCurrentIterationData.html',1,'']]],
  ['custom_20weights_163',['Why we need custom weights',['../md_docs_2user-guide_2trajectory-investment_2merge-weights.html#autotoc_md347',1,'']]],
  ['cut_5fcoefficient_5ftolerance_20tt_164',['&lt;tt&gt;cut_coefficient_tolerance&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md292',1,'']]],
  ['cutsmanagerruntime_165',['CutsManagerRunTime',['../classOuterloop_1_1CutsManagerRunTime.html',1,'Outerloop']]]
];
