var searchData=
[
  ['i_20datadir_20tt_0',['&lt;tt&gt;-i, --dataDir&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md170',1,'']]],
  ['ibendersproblemprovider_1',['IBendersProblemProvider',['../classIBendersProblemProvider.html',1,'']]],
  ['iconfig_2',['IConfig',['../structCatch_1_1IConfig.html',1,'Catch']]],
  ['icontext_3',['IContext',['../structCatch_1_1IContext.html',1,'Catch']]],
  ['icriterioninputdatareader_4',['ICriterionInputDataReader',['../classBenders_1_1Criterion_1_1ICriterionInputDataReader.html',1,'Benders::Criterion']]],
  ['icutsmanager_5',['ICutsManager',['../classOuterloop_1_1ICutsManager.html',1,'Outerloop']]],
  ['id_6',['1- Read candidates and get link column ID',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md125',1,'']]],
  ['id_20mapping_20file_7',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md131',1,'']]],
  ['iexceptiontranslator_8',['IExceptionTranslator',['../structCatch_1_1IExceptionTranslator.html',1,'Catch']]],
  ['iexceptiontranslatorregistry_9',['IExceptionTranslatorRegistry',['../structCatch_1_1IExceptionTranslatorRegistry.html',1,'Catch']]],
  ['igenerator_10',['IGenerator',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igenerator_3c_20float_20_3e_11',['IGenerator&lt; Float &gt;',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igenerator_3c_20integer_20_3e_12',['IGenerator&lt; Integer &gt;',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igenerator_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_13',['IGenerator&lt; std::vector&lt; T &gt; &gt;',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igeneratortracker_14',['IGeneratorTracker',['../structCatch_1_1IGeneratorTracker.html',1,'Catch']]],
  ['illegal_5fchars_15',['illegal_chars',['../structAdditionalConstraintsReader.html#a1d529a309d6dcd07eca227181276a10c',1,'AdditionalConstraintsReader']]],
  ['illegalcharsincandidatename_16',['IllegalCharsInCandidateName',['../classantares__xpansion_1_1input__checker_1_1IllegalCharsInCandidateName.html',1,'antares_xpansion::input_checker']]],
  ['ilogger_17',['ILogger',['../classILogger.html',1,'']]],
  ['iloggermock_18',['ILoggerMock',['../structILoggerMock.html',1,'']]],
  ['iloggerxpansion_19',['ILoggerXpansion',['../structILoggerXpansion.html',1,'']]],
  ['imasterupdate_20',['IMasterUpdate',['../classOuterloop_1_1IMasterUpdate.html',1,'Outerloop']]],
  ['impedances_5f_21',['impedances_',['../structLinkdataRecord_1_1FileColumns.html#ad65a0ad193fd24591ac5d17f074a419b',1,'LinkdataRecord::FileColumns']]],
  ['important_22',['Important',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md13',1,'']]],
  ['imutablecontext_23',['IMutableContext',['../structCatch_1_1IMutableContext.html',1,'Catch']]],
  ['imutableenumvaluesregistry_24',['IMutableEnumValuesRegistry',['../structCatch_1_1IMutableEnumValuesRegistry.html',1,'Catch']]],
  ['imutableregistryhub_25',['IMutableRegistryHub',['../structCatch_1_1IMutableRegistryHub.html',1,'Catch']]],
  ['in_20antares_20xpansion_26',['The optimal investment problem in Antares-Xpansion',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'']]],
  ['in_20direct_20link_20profile_20tt_27',['in direct link profile tt',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md153',1,'&lt;tt&gt;[in]direct-link-profile&lt;/tt&gt;'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md154',1,'&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;']]],
  ['in_20flexibility_28',['Investment in flexibility',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md190',1,'']]],
  ['in_20renewable_20generation_20capacity_29',['Investment in renewable generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md189',1,'']]],
  ['in_20thermal_20generation_20capacity_30',['Investment in thermal generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md188',1,'']]],
  ['in_20transmission_20capacity_20between_20two_20areas_31',['Investment in transmission capacity between two areas',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md187',1,'']]],
  ['in_20tt_20adequacy_5fcriterion_20yml_20tt_32',['Input data for adequacy criterion in &lt;tt&gt;adequacy_criterion.yml&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md139',1,'']]],
  ['in_20tt_20candidates_20ini_20tt_33',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md143',1,'']]],
  ['in_20ubuntu_20are_20known_20to_20have_20mpi_20related_20issues_20please_20use_20the_20other_20ones_34',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md24',1,'']]],
  ['index_35',['index',['../md_docs_2index.html',1,'']]],
  ['indirect_5flink_5fprofile_36',['indirect_link_profile',['../classLinkProfile.html#adf7b5092f19ec8f5f63ce3b8fd69aba7',1,'LinkProfile']]],
  ['indirectcapacity_5f_37',['indirectCapacity_',['../structLinkdataRecord_1_1FileColumns.html#a729097b7eca4ae27add0d332decf53d9',1,'LinkdataRecord::FileColumns']]],
  ['indirecthurdlescost_5f_38',['indirectHurdlesCost_',['../structLinkdataRecord_1_1FileColumns.html#adfed6f095294c0bb8db291926594dd40',1,'LinkdataRecord::FileColumns']]],
  ['info_20file_39',['Output : Nodal Lp Info file',['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html#autotoc_md255',1,'']]],
  ['info_20file_40',['info file',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md244',1,' Nodal lp info file'],['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md243',1,'Master merger info file']]],
  ['information_41',['Loading License Information',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md107',1,'']]],
  ['ini_20tt_42',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md143',1,'']]],
  ['ini_20tt_20file_43',['ini tt file',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md144',1,'Overview of the &lt;tt&gt;candidates.ini&lt;/tt&gt; file'],['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md204',1,'Overview of the &lt;tt&gt;settings.ini&lt;/tt&gt; file']]],
  ['inifilenotfound_44',['IniFileNotFound',['../classantares__xpansion_1_1candidates__reader_1_1IniFileNotFound.html',1,'antares_xpansion.candidates_reader.IniFileNotFound'],['../classantares__xpansion_1_1general__data__reader_1_1IniFileNotFound.html',1,'antares_xpansion.general_data_reader.IniFileNotFound'],['../classIniFileNotFound.html',1,'IniFileNotFound']]],
  ['inireader_45',['INIReader',['../classINIReader.html',1,'']]],
  ['inireader_46',['IniReader',['../classantares__xpansion_1_1general__data__reader_1_1IniReader.html',1,'antares_xpansion::general_data_reader']]],
  ['inireaderutils_47',['IniReaderUtils',['../classIniReaderUtils.html',1,'']]],
  ['init_48',['init',['../classWorker.html#a3cb29b6fca63283d104fe424cd2adbde',1,'Worker::init()'],['../classProblem.html#a075abb3bc479adb0de6c2326fe03ac17',1,'Problem::init()'],['../classSolverAbstract.html#a31e69eec019d489b31b2080f890cecb6',1,'SolverAbstract::init()'],['../classSolverCbc.html#a1b3d4706655309b6d8143d96343069ae',1,'SolverCbc::init()'],['../classSolverClp.html#a8a7c0625768b415c59c59bcdaaf6b6a9',1,'SolverClp::init()'],['../classSolverXpress.html#a30b56a03a4c060bbabf2bb6fc1faa4d3',1,'SolverXpress::init()'],['../classNOOPSolver.html#a4fdde5f69713afe397c251704c2de051',1,'NOOPSolver::init()']]],
  ['init_5fdata_49',['init_data',['../classBendersBase.html#a62a819640d2a7530fce9418547f45d65',1,'BendersBase::init_data()'],['../classBendersSequentialDouble.html#a33c0199bf9a762b001db1f631ca9444f',1,'BendersSequentialDouble::init_data()'],['../classBendersBaseDouble.html#abec4d97a2176e8747fdf4c6cbb94a8cd',1,'BendersBaseDouble::init_data()']]],
  ['initial_20weekly_20problems_50',['Initial weekly problems',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md127',1,'']]],
  ['initialize_51',['initialize',['../classOutput_1_1JsonWriter.html#aee3cc2a6e0300509d23bbbb8de1eae94',1,'Output::JsonWriter::initialize()'],['../classOutput_1_1OutputWriter.html#a3a0f989f5e057b16bf4ead25ab992f05',1,'Output::OutputWriter::initialize()'],['../classOutput_1_1VoidWriter.html#ad6904d7f602e37270c000a9dbe564cde',1,'Output::VoidWriter::initialize()'],['../classXpansion_1_1Test_1_1InMemoryWriter.html#a0711ca27e8c1fd83a4dbcd5376be9150',1,'Xpansion::Test::InMemoryWriter::initialize()'],['../classXpansion_1_1Test_1_1WriterNOOPStub.html#a46fd1d525db02b1601910b5ffff0fc43',1,'Xpansion::Test::WriterNOOPStub::initialize()']]],
  ['initializeproblems_52',['InitializeProblems',['../classBendersMpi.html#a217d3af6fbe78082f30fa9ef75cf1dfb',1,'BendersMpi::InitializeProblems()'],['../classGridSearch.html#adae8b182696920e0932715fdf8247525',1,'GridSearch::InitializeProblems()']]],
  ['initsubproblems_53',['InitSubProblems',['../classGridEvaluator.html#a429fa53f0375c186f366e7007ca25486',1,'GridEvaluator']]],
  ['initxpressenv_54',['initXpressEnv',['../classLoadXpress_1_1XpressLoader.html#a1a17e7973088bd65105007a7e2f2481e',1,'LoadXpress::XpressLoader']]],
  ['inmemorywriter_55',['InMemoryWriter',['../classXpansion_1_1Test_1_1InMemoryWriter.html',1,'Xpansion::Test']]],
  ['input_20data_20for_20adequacy_20criterion_20in_20tt_20adequacy_5fcriterion_20yml_20tt_56',['Input data for adequacy criterion in &lt;tt&gt;adequacy_criterion.yml&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md139',1,'']]],
  ['input_20file_57',['User input file',['../md_docs_2user-guide_2trajectory-investment_2user-input.html#autotoc_md262',1,'']]],
  ['input_20file_20creation_58',['Sensitivity input file creation',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md200',1,'']]],
  ['input_20file_20parsing_59',['User input file parsing',['../md_docs_2user-guide_2trajectory-investment_2user-input.html',1,'']]],
  ['input_20files_20from_20each_20annual_20study_60',['Input files from each annual study',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md245',1,'']]],
  ['inputparameters_61',['InputParameters',['../classantares__xpansion_1_1xpansionConfig_1_1InputParameters.html',1,'antares_xpansion::xpansionConfig']]],
  ['inputparser_62',['InputParser',['../classantares__xpansion_1_1input__parser_1_1InputParser.html',1,'antares_xpansion::input_parser']]],
  ['inputtranslationdriver_63',['InputTranslationDriver',['../classdriver__input__translation_1_1InputTranslationDriver.html',1,'driver_input_translation']]],
  ['install_64',['Dependencies install',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html',1,'']]],
  ['install_20with_20a_20vcpkg_20package_20manager_65',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md83',1,'']]],
  ['installation_66',['Installation',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md101',1,'Default Installation'],['../md_docs_2user-guide_2get-started_2installation.html',1,'Installation'],['../index.html#autotoc_md5',1,'Installation'],['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md102',1,'Non-Default Installation']]],
  ['installation_20details_67',['Build and installation details',['../md_docs_2developer-guide_2install__from__sources_20-INSTALL.html#autotoc_md76',1,'']]],
  ['installation_20instruction_68',['Installation instruction',['../md_docs_2user-guide_2get-started_2installation.html#autotoc_md163',1,'']]],
  ['installed_20capacity_20tt_69',['&lt;tt&gt;already-installed-capacity&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md152',1,'']]],
  ['installed_20in_20direct_20link_20profile_20tt_70',['&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md154',1,'']]],
  ['installer_20creation_71',['Installer creation',['../md_docs_2developer-guide_2install__from__sources_25-Installer-creation.html',1,'']]],
  ['installing_20dependencies_72',['Installing dependencies',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md85',1,'']]],
  ['installing_20xpress_73',['Installing Xpress',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md100',1,'']]],
  ['installing_20xpress_20solver_20and_20loading_20it_20dynamically_74',['Installing Xpress Solver and Loading it Dynamically',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html',1,'']]],
  ['instancedata_75',['InstanceData',['../classInstanceData.html',1,'']]],
  ['instruction_76',['Installation instruction',['../md_docs_2user-guide_2get-started_2installation.html#autotoc_md163',1,'']]],
  ['interco_20txt_20tt_77',['The file &lt;tt&gt;interco.txt&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md121',1,'']]],
  ['intercofiledata_78',['IntercoFileData',['../structIntercoFileData.html',1,'']]],
  ['intercofilesexception_79',['IntercoFilesException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1IntercoFilesException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['interpretation_80',['Results interpretation',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md198',1,'']]],
  ['introduction_81',['Introduction',['../md_docs_2developer-guide_2install__from__sources_20-INSTALL.html',1,'Introduction'],['../index.html#autotoc_md1',1,'Introduction'],['../md_docs_2index.html#autotoc_md135',1,'Introduction']]],
  ['invalidboundtypeexception_82',['InvalidBoundTypeException',['../classInvalidBoundTypeException.html',1,'']]],
  ['invalidcandidates_83',['InvalidCandidates',['../classtrajectory__module_1_1TrajectoryModule_1_1InvalidCandidates.html',1,'trajectory_module.TrajectoryModule.InvalidCandidates'],['../classuser__input__translation_1_1TrajectoryModule_1_1InvalidCandidates.html',1,'user_input_translation.TrajectoryModule.InvalidCandidates']]],
  ['invalidcolsizeexception_84',['InvalidColSizeException',['../classInvalidColSizeException.html',1,'']]],
  ['invalidcoltypeexception_85',['InvalidColTypeException',['../classInvalidColTypeException.html',1,'']]],
  ['invalidhourforprofile_86',['InvalidHourForProfile',['../classLinkProfile_1_1InvalidHourForProfile.html',1,'LinkProfile']]],
  ['invalidintercofile_87',['InvalidIntercoFile',['../classCandidatesINIReader_1_1InvalidIntercoFile.html',1,'CandidatesINIReader']]],
  ['invalidmasterstructurefileexception_88',['InvalidMasterStructureFileException',['../classInvalidMasterStructureFileException.html',1,'']]],
  ['invalidnumberofargumentspassedtoparser_89',['InvalidNumberOfArgumentsPassedToParser',['../classOptionsParser_1_1InvalidNumberOfArgumentsPassedToParser.html',1,'OptionsParser']]],
  ['invalidrootstudypatherror_90',['InvalidRootStudyPathError',['../classdriver__input__translation_1_1InputTranslationDriver_1_1InvalidRootStudyPathError.html',1,'driver_input_translation::InputTranslationDriver']]],
  ['invalidrowsizeexception_91',['InvalidRowSizeException',['../classInvalidRowSizeException.html',1,'']]],
  ['invalidsimulationname_92',['InvalidSimulationName',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1InvalidSimulationName.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['invalidsolverforcopyexception_93',['InvalidSolverForCopyException',['../classInvalidSolverForCopyException.html',1,'']]],
  ['invalidsolvernameexception_94',['InvalidSolverNameException',['../classInvalidSolverNameException.html',1,'']]],
  ['invalidsolveroptionexception_95',['InvalidSolverOptionException',['../classInvalidSolverOptionException.html',1,'']]],
  ['invalidsolverstatusexception_96',['InvalidSolverStatusException',['../classInvalidSolverStatusException.html',1,'']]],
  ['invalidstatusexception_97',['InvalidStatusException',['../classInvalidStatusException.html',1,'']]],
  ['invalidstructurefile_98',['InvalidStructureFile',['../structInvalidStructureFile.html',1,'']]],
  ['invalidtrajectoryconstraint_99',['InvalidTrajectoryConstraint',['../classtrajectory__module_1_1TrajectoryModule_1_1InvalidTrajectoryConstraint.html',1,'trajectory_module.TrajectoryModule.InvalidTrajectoryConstraint'],['../classuser__input__translation_1_1TrajectoryModule_1_1InvalidTrajectoryConstraint.html',1,'user_input_translation.TrajectoryModule.InvalidTrajectoryConstraint']]],
  ['invalidtreestructure_100',['InvalidTreeStructure',['../classtrajectory__module_1_1TrajectoryModule_1_1InvalidTreeStructure.html',1,'trajectory_module.TrajectoryModule.InvalidTreeStructure'],['../classuser__input__translation_1_1TrajectoryModule_1_1InvalidTreeStructure.html',1,'user_input_translation.TrajectoryModule.InvalidTreeStructure']]],
  ['invalidyearsweightnumber_101',['InvalidYearsWeightNumber',['../classantares__xpansion_1_1xpansion__study__reader_1_1XpansionStudyReader_1_1InvalidYearsWeightNumber.html',1,'antares_xpansion.xpansion_study_reader.XpansionStudyReader.InvalidYearsWeightNumber'],['../classWeightsFileReader_1_1InvalidYearsWeightNumber.html',1,'WeightsFileReader::InvalidYearsWeightNumber']]],
  ['invalidyearsweightvalue_102',['InvalidYearsWeightValue',['../classantares__xpansion_1_1xpansion__study__reader_1_1XpansionStudyReader_1_1InvalidYearsWeightValue.html',1,'antares_xpansion.xpansion_study_reader.XpansionStudyReader.InvalidYearsWeightValue'],['../classWeightsFileReader_1_1InvalidYearsWeightValue.html',1,'WeightsFileReader::InvalidYearsWeightValue']]],
  ['invested_20capacity_20and_20capacity_20of_20the_20antares_20study_103',['Link between invested capacity and capacity of the Antares study',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md155',1,'']]],
  ['invested_20capacity_20and_20investment_20cost_104',['Invested capacity and investment cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md228',1,'']]],
  ['investment_20candidates_105',['investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md194',1,'Additional characteristics for links of investment candidates'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md192',1,'Fixed-cost annuity for investment candidates']]],
  ['investment_20candidates_20in_20tt_20candidates_20ini_20tt_106',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md143',1,'']]],
  ['investment_20candidates_20on_20the_20same_20link_107',['Several investment candidates on the same link',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md159',1,'']]],
  ['investment_20cost_108',['Invested capacity and investment cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md228',1,'']]],
  ['investment_20in_20flexibility_109',['Investment in flexibility',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md190',1,'']]],
  ['investment_20in_20renewable_20generation_20capacity_110',['Investment in renewable generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md189',1,'']]],
  ['investment_20in_20thermal_20generation_20capacity_111',['Investment in thermal generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md188',1,'']]],
  ['investment_20in_20transmission_20capacity_20between_20two_20areas_112',['Investment in transmission capacity between two areas',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md187',1,'']]],
  ['investment_20problem_113',['Investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md234',1,'']]],
  ['investment_20problem_114',['investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md236',1,'Benders reformulation of the investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md233',1,'Constraints (for the investment problem)'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'Mathematical aspects of the investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md239',1,'Reliability-constrained investment problem'],['../md_docs_2user-guide_2trajectory-investment_2trajectory-problem.html',1,'Trajectory investment problem']]],
  ['investment_20problem_20generation_115',['Investment problem generation',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html',1,'']]],
  ['investment_20problem_20generation_3a_20tt_20problem_5fgeneration_20tt_116',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md111',1,'']]],
  ['investment_20problem_20in_20antares_20xpansion_117',['The optimal investment problem in Antares-Xpansion',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'']]],
  ['investment_20tt_118',['&lt;tt&gt;max-investment&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md149',1,'']]],
  ['investment_20variables_119',['Investment variables',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html#autotoc_md223',1,'']]],
  ['investmentvariabletypeenum_120',['InvestmentVariableTypeEnum',['../classtrajectory__module_1_1InvestmentVariableTypeEnum.html',1,'trajectory_module.InvestmentVariableTypeEnum'],['../classuser__input__translation_1_1InvestmentVariableTypeEnum.html',1,'user_input_translation.InvestmentVariableTypeEnum']]],
  ['iproblemproviderport_121',['IProblemProviderPort',['../classIProblemProviderPort.html',1,'']]],
  ['iproblemvariablesproviderport_122',['IProblemVariablesProviderPort',['../classIProblemVariablesProviderPort.html',1,'']]],
  ['iproblemwriter_123',['IProblemWriter',['../classIProblemWriter.html',1,'']]],
  ['iregistryhub_124',['IRegistryHub',['../structCatch_1_1IRegistryHub.html',1,'Catch']]],
  ['iresultcapture_125',['IResultCapture',['../structCatch_1_1IResultCapture.html',1,'Catch']]],
  ['irunner_126',['IRunner',['../structCatch_1_1IRunner.html',1,'Catch']]],
  ['is_5faccurate_127',['is_accurate',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a0c3fa0cf225d9b7bb06864a8aa7f1b45',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['is_5fcallable_128',['is_callable',['../structCatch_1_1is__callable.html',1,'Catch']]],
  ['is_5fcallable_3c_20fun_28args_2e_2e_2e_29_3e_129',['is_callable&lt; Fun(Args...)&gt;',['../structCatch_1_1is__callable_3_01Fun_07Args_8_8_8_08_4.html',1,'Catch']]],
  ['is_5fcallable_5ftester_130',['is_callable_tester',['../structCatch_1_1is__callable__tester.html',1,'Catch']]],
  ['is_5frange_131',['is_range',['../structCatch_1_1is__range.html',1,'Catch']]],
  ['is_5frange_5fimpl_132',['is_range_impl',['../structCatch_1_1detail_1_1is__range__impl.html',1,'Catch::detail']]],
  ['is_5frange_5fimpl_3c_20t_2c_20typename_20void_5ftype_3c_20decltype_28begin_28std_3a_3adeclval_3c_20t_20_3e_28_29_29_29_3e_3a_3atype_20_3e_133',['is_range_impl&lt; T, typename void_type&lt; decltype(begin(std::declval&lt; T &gt;()))&gt;::type &gt;',['../structCatch_1_1detail_1_1is__range__impl_3_01T_00_01typename_01void__type_3_01decltype_07begin_0efe009a05f00a00c1e4e06989d122a22.html',1,'Catch::detail']]],
  ['is_5frelaxed_134',['is_relaxed',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a4b43dd57f999df86ffacede36f47e197',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['isnot_135',['IsNot',['../classStringManip_1_1IsNot.html',1,'StringManip']]],
  ['isstreaminsertable_136',['IsStreamInsertable',['../classCatch_1_1Detail_1_1IsStreamInsertable.html',1,'Catch::Detail']]],
  ['issubproblemused_137',['IsSubproblemUsed',['../classGridEvaluator.html#a2efaf82d89f49c2491813c6b6e3ac6bd',1,'GridEvaluator']]],
  ['issues_20please_20use_20the_20other_20ones_138',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md24',1,'']]],
  ['istream_139',['IStream',['../structCatch_1_1IStream.html',1,'Catch']]],
  ['it_20dynamically_140',['Installing Xpress Solver and Loading it Dynamically',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html',1,'']]],
  ['iteration_141',['Iteration',['../structOutput_1_1Iteration.html',1,'Output']]],
  ['iterationresultlog_142',['IterationResultLog',['../classxpansion_1_1logger_1_1IterationResultLog.html',1,'xpansion::logger']]],
  ['iterationsdata_143',['IterationsData',['../structOutput_1_1IterationsData.html',1,'Output']]],
  ['iteratorgenerator_144',['IteratorGenerator',['../classCatch_1_1Generators_1_1IteratorGenerator.html',1,'Catch::Generators']]],
  ['itestcaseregistry_145',['ITestCaseRegistry',['../structCatch_1_1ITestCaseRegistry.html',1,'Catch']]],
  ['itestinvoker_146',['ITestInvoker',['../structCatch_1_1ITestInvoker.html',1,'Catch']]],
  ['itransientexpression_147',['ITransientExpression',['../structCatch_1_1ITransientExpression.html',1,'Catch']]],
  ['iwriterlogger_148',['IWriterLogger',['../classIWriterLogger.html',1,'']]],
  ['ixpansionproblemsprovider_149',['IXpansionProblemsProvider',['../classIXpansionProblemsProvider.html',1,'']]]
];
